name: Remote Docker
author: Friends of Go (it@friendsofgo.tech)
description: A GitHub Action that supports Docker remotely
branding:
  color: blue
  icon: play
inputs:
  hostAddress:
    description: 'Deployment host address'
    required: true
  caCert:
    description: 'CA certificate'
    required: true
  serverCert:
    description: 'Server certificate'
    required: true
  serverKey:
    description: 'Server key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'